#!/bin/bash

# Prints out battery percentage

CHARGING_ICON='charging'
WARNING_ICON='BAT LOW'


BAT_ICON="bat:"
ICON="bat:"

get_battery()
{
        # The vast majority of people only use one battery.

        if [ -d /sys/class/power_supply/BAT0 ]; then
                capacity=$(cat /sys/class/power_supply/BAT0/capacity)
                charging=$(cat /sys/class/power_supply/BAT0/status)
                if [[ "$charging" == "Charging" ]]; then
                        ICON="$CHARGING_ICON"
                elif [[ $capacity -le 25 ]]; then
                        ICON="$WARNING_ICON"
                fi
        fi
        echo "$BAT_ICON$capacity%"
}

get_battery



