#!/bin/bash

# Prints out the bluetooth status

BLUETOOTH_ON_ICON='bt:on'
BLUETOOTH_OFF_ICON='bt:off'

get_bluetooth()
{
    status=$(systemctl is-active bluetooth.service)

    if [ "$status" == "active" ]
    then
        echo "$BLUETOOTH_ON_ICON"
    else
        :
        echo "$BLUETOOTH_OFF_ICON"
    fi
}

get_bluetooth
