#!/bin/bash

# Gets temperature of the CPU
# Dependencies: lm_sensors

PREFIX='cpu:'


WARNING_LEVEL=80

get_cputemp()
{
	# CPU_T=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon?/temp2_input)
	# CPU_TEMP=$(expr $CPU_T / 1000)

	CPU_TEMP="$(sensors | grep temp1 | awk 'NR==1{gsub("+", " "); gsub("\\..", " "); print $2}')"
	echo "$PREFIX$CPU_TEMP°C"
}

get_cputemp
